name: Deploy to GitHub Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout config-repo
        uses: actions/checkout@v2
        with:
          repository: jayarnim/TechLog-config
          token: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Set Git user
        run: |
          git config --global user.email "jayarnim727@gmail.com"
          git config --global user.name "jayarnim"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: jayarnim/jayarnim.github.io
          publish_branch: main
          publish_dir: ./_site