name: Publish

on:
  push:
    branches:
      - main
  workflow_call:
    secrets:
      ACTIONS_DEPLOY_KEY:
        required: true
      BUILDER:
        required: true

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.ACTIONS_DEPLOY_KEY }}" \
            https://api.github.com/repos/${{ secrets.BUILDER }}/dispatches \
            -d '{"event_type":"deploy", "client_payload":{"branch": "${{ github.ref_name }}"}}'